import { Lead, Stage, Pipeline } from '@/types/crm';

export const mockStages: Stage[] = [
  { id: 'stage-1', pipelineId: 'pipeline-1', name: 'Novo contato', order: 0, color: '#6b7280', createdAt: new Date(), updatedAt: new Date() },
  { id: 'stage-2', pipelineId: 'pipeline-1', name: 'Diagnóstico agendado', order: 1, color: '#3b82f6', createdAt: new Date(), updatedAt: new Date() },
  { id: 'stage-3', pipelineId: 'pipeline-1', name: 'Call realizada', order: 2, color: '#10b981', createdAt: new Date(), updatedAt: new Date() },
  { id: 'stage-4', pipelineId: 'pipeline-1', name: 'Follow-up', order: 3, color: '#f59e0b', createdAt: new Date(), updatedAt: new Date() },
  { id: 'stage-5', pipelineId: 'pipeline-1', name: 'Fechado (ganho)', order: 4, color: '#059669', createdAt: new Date(), updatedAt: new Date() },
  { id: 'stage-6', pipelineId: 'pipeline-1', name: 'Fechado (perdido)', order: 5, color: '#dc2626', createdAt: new Date(), updatedAt: new Date() },
];

export const mockPipeline: Pipeline = {
  id: 'pipeline-1',
  name: 'Pipeline Padrão',
  createdBy: 'user-1',
  stages: mockStages,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    name: 'Carlos Dominante',
    phone: '+5531999991111',
    email: 'carlos@example.com',
    source: 'Instagram',
    ownerId: 'user-1',
    pipelineId: 'pipeline-1',
    stageId: 'stage-1',
    discProfile: 'D',
    dealValue: 5000,
    tags: ['urgente', 'decisor'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lead-2',
    name: 'Isabela Influente',
    phone: '+5531999992222',
    email: 'isabela@example.com',
    source: 'WhatsApp',
    ownerId: 'user-1',
    pipelineId: 'pipeline-1',
    stageId: 'stage-1',
    discProfile: 'I',
    dealValue: 3500,
    tags: ['entusiasta'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lead-3',
    name: 'Sandra Estável',
    phone: '+5531999993333',
    email: 'sandra@example.com',
    source: 'Indicação',
    ownerId: 'user-1',
    pipelineId: 'pipeline-1',
    stageId: 'stage-2',
    discProfile: 'S',
    dealValue: 4000,
    tags: ['segurança'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lead-4',
    name: 'Claudio Cauteloso',
    phone: '+5531999994444',
    email: 'claudio@example.com',
    source: 'Site',
    ownerId: 'user-1',
    pipelineId: 'pipeline-1',
    stageId: 'stage-2',
    discProfile: 'C',
    dealValue: 6000,
    tags: ['analitico'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
